### PR TITLE
eject the timewaster. begone!

### PR DESCRIPTION
**Pull request by mor1**
(FTAOD that's me that is :)

Signed-off-by: Richard Mortier <mort@cantab.net>

### CODE REVIEW

**Review by djs55 — APPROVED** [review]
I think "timewaster" is a bit harsh!

**Comment by mor1** [comment]
Just saying it like I see it... :)

(Thanks!)

**Comment by talex5** [comment]
Ejected! Update should be live now.

**Comment by avsm** [comment]
You say timewaster like it's a bad thing....

**Comment by mor1** [comment]
https://www.youtube.com/watch?v=f6EXBtKtC9Y

**Pull request merged**
