### PR TITLE
Add post for Irmin 1.0

### PR DESCRIPTION
**Pull request by samoht**

### CODE REVIEW

**Comment by samoht** [comment]
Thanks very much @yomimono! I've completed the TODO, so I think this is ready to go. I am not so sure it's interesting/useful but well at least that's some words...

**Comment by yomimono** [comment]
I didn't have solid enough Internet access to merge this on Friday.  @samoht, could you change the date and merge today?  The article looks good to me.

**Comment by samoht** [comment]
Ok I'll do that around 1-2pm UK time. Any idea for the title?

**Comment by dbuenzli** [comment]
I didn't have the time to go through the post but a skim suggest something like "Easy distributed analytics with Irmin 1.0"

**Comment by yomimono** [comment]
Not really! :sweat_smile: Maybe something like "Announcing Irmin 1.0: Simpler Merges, Better Trees, More Independence"?  But maybe without the subtitle it's better...

**Comment by dbuenzli** [comment]
@yomimono I wouldn't put the emphasis on the features and the `1.0`, my guess is that the audience that has used `Irmin` is minimal so they don't know what that would really mean. Focusing on a good application might entice people to get interested in the tech.

**Comment by samoht** [comment]
I am merging now. Hopefully the post will be pushed online in a finite amount of time.

**Comment by samoht** [comment]
Gah, TravisCI still hasn't started to build my post...

**Pull request merged**
