### PR TITLE
Functoria

### PR DESCRIPTION
**Pull request by samoht**
This is #389 plus some fixes to make the deployment work

### CODE REVIEW

**Comment by Drup** [comment]
> The match_impl is a bit annoying to use, would be nice to have a predicate
to apply on the `b.

Is that better ?
```ocaml
if_impl Key.(map ((=) None) @@ value pr))
  ...
```

**Comment by samoht** [comment]
Thanks, both issues are fixed.

**Comment by samoht** [comment]
Great it's green. Now need to be sure that the deployed image use fat and not crunch.

**Comment by hannesm** [comment]
...and mirage.io is down...

**Comment by samoht** [comment]
This is failing because of:

```
Xen Minimal OS!
Initialising timer interface
Initialising console ... done.
getenv(OCAMLRUNPARAM) -> null
getenv(CAMLRUNPARAM) -> null
getenv(PATH) -> null
Unsupported function lseek called in Mini-OS kernel
Unsupported function lseek called in Mini-OS kernel
Unsupported function lseek called in Mini-OS kernel
getenv(OCAMLRUNPARAM) -> null
getenv(CAMLRUNPARAM) -> null
getenv(TMPDIR) -> null
getenv(TEMP) -> null
Netif: add resume hook
Blkif: add resume hook
getenv(DEBUG) -> null
getenv(OMD_DEBUG) -> null
getenv(OMD_FIX) -> null
getenv(REDIRECT) -> null
getenv(HOST) -> null
Netif.connect 0
Block.connect 51808: unable to match '51808' to any available devices [ 51744 ]
Block.connect 51808: could not find device
Netfront.create: id=0 domid=0
 sg:true gso_tcpv4:true rx_copy:true rx_flip:false smart_poll:false
MAC: 00:16:3e:3d:9d:6e
Attempt to open(/dev/urandom)!
Unsupported function getpid called in Mini-OS kernel
Unsupported function getppid called in Mini-OS kernel
Manager: connect
Manager: configuring
Manager: Interface to 46.43.42.146 nm 255.255.255.128 gw [46.43.42.129]

ARP: sending gratuitous from 46.43.42.146
Manager: configuration done
Fatal error: exception Failure("block61")
Raised at file "src/core/lwt.ml", line 789, characters 22-23
Called from file "lib/main.ml", line 58, characters 10-20
Called from file "main.ml", line 267, characters 5-10
Mirage exiting with status 2
Do_exit called!
```

**Comment by samoht** [comment]
I've reverted to https://github.com/mirage/mirage-www-deployment/commit/16798e7a0384cf38174a088d4d6cf94ca9f22f28

**Pull request merged**
