### PR TITLE
Remove warnings and fix compilation with mirage.3.7.2

### PR DESCRIPTION
**Pull request by samoht**
/cc @hannesm

### CODE REVIEW

**Comment by samoht** [comment]
No idea how to fix this:

```
The following dependencies couldn't be met:
  - mirage-unikernel-mirageio-xen → fat-filesystem < 0.13.0 → ocaml < 4.06.0
      base of this switch (use `--unlock-base' to force)
  - mirage-unikernel-mirageio-xen → fat-filesystem < 0.13.0 → mirage-fs < 3.0.0
    → mirage < 2.0.0 → ocaml < 4.06.0
      base of this switch (use `--unlock-base' to force)
  - mirage-unikernel-mirageio-xen → fat-filesystem < 0.13.0 → lwt < 2.6.0 →
    ocaml < 4.05.0
      base of this switch (use `--unlock-base' to force)
  - mirage-unikernel-mirageio-xen → fat-filesystem < 0.13.0 → io-page < 1.3.0 →
    ocaml < 4.06.0
      base of this switch (use `--unlock-base' to force)
  - mirage-unikernel-mirageio-xen → mirage-fs >= 3.0.0
      unmet availability conditions, e.g. false
Your request can't be satisfied:
  - No available version of mirage-fs satisfies the constraints
```

**Comment by hannesm** [comment]
oh, a first user of fat, it's pretty simple: merge https://github.com/mirage/ocaml-fat/pull/83 and do a `fat` release :)

**Comment by samoht** [comment]
The new release is there: https://github.com/ocaml/opam-repository/pull/15355

There are a lot of warnings due to the deprecation of Mirage_fs, I've tried to fix them but it was a bit too painful so I gave up.

**Comment by samoht** [comment]
Jobs restarted now that fat-filesystem.0.14 is released

**Comment by hannesm** [comment]
hmm, it looks like `mirage` contains wrong `fat-filesystem` bounds that need to be adjusted and a mirage 3.7.2 be released -- https://github.com/mirage/mirage/blob/master/lib/mirage_impl_fs.ml#L13

**Comment by hannesm** [comment]
https://github.com/mirage/mirage/pull/1015 should fix that..

**Comment by samoht** [comment]
Thanks, I'll make a new mirage release with these changes.

**Comment by samoht** [comment]
mirage 3.7.2 release there: https://github.com/ocaml/opam-repository/pull/15361

**Comment by samoht** [comment]
Restarted again now that mirage 3.7.2 is out.

**Comment by samoht** [comment]
restarted again now that https://github.com/ocaml/opam-repository/pull/15364 is merged

**Comment by samoht** [comment]
I need to fix `dispatch_tls.ml` now...

**Comment by hannesm** [comment]
looks good, apart from merlin changes -- we should just remove the `.merlin` imho

**Comment by samoht** [comment]
Updated

**Pull request merged**
