### PR TITLE
How to for mirage on arm64

### PR DESCRIPTION
**Pull request by derpeter**
This is a write up on the work we did on the retreat and afterwards to get mirage running with ukvm on arm cpus. As most people will have an rasperrypi or at least can get one much easier than other boards, this howto is written for the pi.

### CODE REVIEW

**Comment by hannesm** [comment]
thanks for the article... the CI failure is due to `js_of_ocaml` not working with `lwt.4.0.0` (fix is waiting to be merged in https://github.com/ocaml/opam-repository/pull/11788)

**Comment by hannesm** [comment]
the last Travis CI job failed with:
```
+make
mirage build
This uses the fat command-line tool to build a simple FAT
filesystem image.
I couldn't find the fat command-line tool.
Try running opam install fat-filesystem
run ['./make-fat_block3-image.sh']: exited with 1make: *** [build] Error 1
'OPAMYES=1 export OPAMYES; set -ex; make' exited 2. Terminating with 2
```

but in the output it installed `fat-filesystem.0.12.1` -- anyone has an idea what may be wrong?  in addition, the other jobs succeeded as well.

**Comment by mato** [comment]
@derpeter Thanks for the write-up. I wonder if the Mirage website is the best place for this kind of information, for several reasons:

1. There is already a dearth of many documents about "How to get X running on ARM board Y" on the web. The problem with these kinds of write-ups is that they tend to go stale pretty quickly, especially if keeping them up to date is behind a comparatively heavy-weight process (PR, review, ...).
2. The write-up is about the low-level details needed to get Solo5/ukvm to run (or specifically, a recent enough Linux to get KVM on ARM64 to work). There is nothing Mirage-specific in it.

Perhaps this would be a good point to start populating a Solo5 Wiki, using the standard Github Wiki feature?

@hannesm @ricarkol @djwillia What do you think?

**Comment by derpeter** [comment]
@mato as you know i'm new to the whole mirage universe, so if there is a better place i'm all in. 
I'm planning on extending the how to for the other boards i have tested so a wiki is probably a good place as its more easy to alter without having somebody to merge the pull request every time. 

So what ever you guys think is the best place works for me.

**Comment by hannesm** [comment]
@mato I am not sure whether yet another (GitHub) wiki for some documentation is a good solution -- but if your desire is to have a web presence for solo5 (including project description, up-to-date documentation, and installation instructions), that should be done.  The mirage.io website is (as mentioned in various other issues of this and mirage/mirage repository) structurally not yet optimal and needs some work imho (I still hope that @samoht will at some point have the re-work of the website done ;).

this specific instructions: I'm happy to merge PRs (once I manage to debug the travis failure in here a bit further), and future PRs.

**Comment by hannesm** [comment]
thanks to @yomimono (who told me about the `fat` executable not being part of `fat-filesystem.0.12.1`, which is now fixed in opam-repository), travis is green here! :)

**Comment by hannesm** [comment]
LGTM (and travis is happy), anyone against merging this for mirage.io? //cc @mirage/core

**Comment by yomimono** [comment]
I'm quite happy to have this writeup live on `mirage.io`, rather than have it languish while we bikeshed the perfect publishing solution. I'm a bit hesitant to merge while those in `mirage.io`'s timezone are (hopefully) not looking at computers, but if nobody else has hit the green button by the time I look at this tomorrow, I'll mash it myself.

**Comment by mor1** [comment]
Lgtm when I looked earlier. Mash away :)
(I'm only looking at a phone though, so don't mash if the concern was about
someone local being able to fix things if the magic scripts break...!)

**Comment by yomimono** [comment]
> don't mash if the concern was about someone local being able to fix things if the magic scripts break...!)

That is indeed my concern :)

**Comment by samoht** [comment]
LGTM

**Pull request merged**
