### PR TITLE
Tls tools

### PR DESCRIPTION
**Pull request by hannesm**

### CODE REVIEW

**Comment by avsm** [comment]
mirage-www build broken atm on master?

```
File "main.ml", line 91, characters 18-39:
Error: Unbound module Conduit_mirage.No_TLS
```

**Comment by samoht** [comment]
Can you rebase with master?

**Comment by hannesm** [comment]
rebased

**Comment by amirmc** [comment]
This looks good! I've restarted the Travis build (although it was green) just in case things have changed in the meantime.  If it's still green, I'll merge this. It still needs an edit to `data.ml` to appear on the live site but that can be done separately.

**Pull request merged**
