### PR TITLE
remove yomimono from core team list

### PR DESCRIPTION
**Pull request by yomimono**

### CODE REVIEW

**Comment by hannesm** [comment]
@mirage/core should we have an `alumni` section (or former members of the core team) -- anyone has a good name for this?

**Comment by mor1** [comment]
That SGTM, for those who wish to be so listed, and "alumni" works for me as a section heading. Equally could just add to the Contributors section.
Perhaps ask @yomimono what she'd prefer as she'd be the first such person :)

**Comment by avsm** [comment]
Alumni also works for me as a section heading.

**Comment by hannesm** [comment]
see #653 which introduces such a section! :)

**Comment by hannesm** [comment]
thanks, merged as part of #653

**Pull request closed without merging**
