### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by abeaumont**

### CODE REVIEW

**Comment by talex5** [comment]
PR looks good, but Travis is failing with:

`rpc is now git-pinned to git://github.com/djs55/rpc-light#fix-build`

@djs55: maybe this pin can be removed?

**Comment by yomimono** [comment]
@djs55 ping?

**Comment by djs55** [comment]
I've removed the PINS and then [forked the ocaml-ci-scripts](https://github.com/mirage/ocaml-ci-scripts/tree/mirage3) so that
- we run `make configure` rather than `mirage configure` in the wrong directory: https://github.com/ocaml/ocaml-ci-scripts/pull/162 (this is a case of the build in this repo being too complicated I think)
- OCaml 4.04.2 is used (as needed by `mirage-xen-ocaml.3.0.4`): ocaml/ocaml-ci-scripts@2e27f0823c623ef1480481b301d0793d1e7c5dd7 
- the `mir-` prefix is used: see this outstanding but blocked PR: https://github.com/ocaml/ocaml-ci-scripts/pull/156

If you rebase this PR to latest master and force push, I think it'll work.

**Comment by djs55** [comment]
Actually I've taken the liberty of rebasing the branch for you -- hope this is ok!

**Comment by djs55** [comment]
Thanks for the fix!

**Pull request merged**
