### PR TITLE
Update the packaging notes

### PR DESCRIPTION
**Pull request by samoht**
Minor update to these great notes. /cc @djs55

### CODE REVIEW

**Comment by samoht** [comment]
An interesting linking error:

```
[K+ ocamlfind ocamlc -g -linkpkg -linkpkg -thread -package bigarray -package rrd -package re.str -package uri -package c3 -package js_of_ocaml.log -package js_of_ocaml.syntax -package js_of_ocaml -package lwt.syntax -syntax camlp4o main.cmo -o main.byte
File "_none_", line 1:
Error: Error while linking /home/travis/.opam/4.03.0/lib/rrd/rrd.cma(Rrd_timescales):
Reference to undefined global `Jsonrpc'
```
Is there something wrong with `xapi-rrd`? /cc @djs55

**Comment by djs55** [comment]
My guess would be that `ppx_deriving_rpc` https://github.com/xapi-project/xcp-rrd/blob/56b6c89d467d51cbc1c9e454707b3c72ab1d7757/_oasis#L17 is inserting references to `Jsonrpc` from https://github.com/mirage/ocaml-rpc and this isn't declared as a dependency somewhere. I assume the `ppx_deriving_rpc` is the compile-time pre-processor but it probably ought to have a runtime component. Is that `rpc`? In the case of `ppx_cstruct` the run-time dependency is `cstruct`.

/cc @jonludlam

**Comment by avsm** [comment]
`opam pin add rpc 1.5.4` fixes it for me

**Comment by samoht** [comment]
Missing deps it seems:

```
=> Lwt 3.0.0 made some minor breaking changes, announced in 2.7.0. See
     https://github.com/ocsigen/lwt/issues/308
make[1]: Leaving directory `/home/travis/build/mirage/mirage-www/stats'
cd stats && make all
make[1]: Entering directory `/home/travis/build/mirage/mirage-www/stats'
ocamlbuild -use-ocamlfind -pkgs lwt.syntax,js_of_ocaml,js_of_ocaml.syntax,js_of_ocaml.log,c3,uri,re.str,rrd,bigarray -tags "syntax(camlp4o),annot,bin_annot,strict_sequence,principal,thread" -tag-line "<static*.*>: -syntax(camlp4o)" -cflag -g -lflags -g,-linkpkg main.byte
+ ocamlfind ocamlc -c -g -annot -bin-annot -principal -thread -strict-sequence -package bigarray -package rrd -package re.str -package uri -package c3 -package js_of_ocaml.log -package js_of_ocaml.syntax -package js_of_ocaml -package lwt.syntax -syntax camlp4o -o main.cmo main.ml
File "main.ml", line 129, characters 19-41:
Error: Unbound module Rrd_timescales
```

**Comment by djs55** [comment]
Also needs
- https://github.com/xapi-project/xcp-rrd/pull/20 on all platforms
- https://github.com/mirage/ocaml-rpc/pull/45 if you want to build on the Mac for Unix
- and https://github.com/mirage/ocaml-vmnet/pull/20 if you want to build on the Mac for vmnet

**Comment by djs55** [comment]
One of the builds fails with
```
This uses the fat command-line tool to build a simple FAT
filesystem image.
I couldn't find the fat command-line tool.
Try running opam install fat-filesystem

run ['./make-fat_block3-image.sh']: exited with 1make[1]: *** [build] Error 1
make[1]: Leaving directory `/home/travis/build/mirage/mirage-www/src'
```

**Comment by djs55** [comment]
The Xen version is still failing because one of the dependencies is linking compiler-libs and
```
+ ocamlfind ocamlopt -g -dontlink unix -dontlink str -dontlink num -dontlink threads -linkpkg -output-obj -package tls.mirage -package tls -package tcpip.udp -package tcpip.tcp -package tcpip.stack-direct -package tcpip.ipv4 -package tcpip.icmpv4 -package tcpip.ethif -package tcpip.arpv4 -package tcpip -package rrd -package ptime -package nocrypto.mirage -package nocrypto -package mirage-xen -package mirage-types-lwt -package mirage-types -package mirage-runtime -package mirage-random -package mirage-net-xen -package mirage-logs -package mirage-http -package mirage-fs-lwt -package mirage-clock-freestanding -package mirage-bootvar-xen -package mirage-block-xen.front -package mirage-block-xen -package lwt -package io-page -package functoria-runtime -package fat-filesystem -package duration -package cowabloga -package cow -package c3 -predicates mirage_xen paper.cmx perf.cmx site_config.cmx data.cmx pages.cmx blog.cmx key_gen.cmx stats.cmx wiki.cmx dispatch.cmx dispatch_tls.cmx static1.cmx static2.cmx main.cmx -o main.native.o
findlib: [WARNING] Interface main.cmi occurs in several directories: ., /home/travis/.opam/4.03.0/lib/ocaml/compiler-libs
findlib: [WARNING] Interface types.cmi occurs in several directories: ., /home/travis/.opam/4.03.0/lib/ocaml/compiler-libs
findlib: [WARNING] Interface config.cmi occurs in several directories: ., /home/travis/.opam/4.03.0/lib/ocaml/compiler-libs
findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /home/travis/.opam/4.03.0/lib/ocaml/compiler-libs, /home/travis/.opam/4.03.0/lib/ocaml
File "_none_", line 1:
Error: Files site_config.cmx
       and /home/travis/.opam/4.03.0/lib/ocaml/compiler-libs/ocamlcommon.cmxa
       make inconsistent assumptions over interface Types
Command exited with code 2.
```

**Comment by djs55** [comment]
And travis is green!

**Comment by samoht** [comment]
@djs55 do you know which Xen library is still linking with compiler libs? Might be worth fixing this :-)

**Comment by djs55** [comment]
It's definitely worth fixing, but I don't know which library is going it :(

**Comment by djs55** [comment]
Reproducing it locally, the problem happens when some package (not sure which) depends on `cstruct < 3.0.0` which brings in old `xen-gnt` which has the packaging bug. It will go away as more packages are updated to use the new `cstruct`.

**Pull request merged**
