### PR TITLE
Add notes on jbuilder and topkg

### PR DESCRIPTION
**Pull request by djs55**
Following my recent experiments I thought it would be a good idea to write down the various "best practices" or "tips and tricks" for using jbuilder and topkg.

Signed-off-by: David Scott <dave@recoil.org>

### CODE REVIEW

**Comment by djs55** [comment]
The other entries in here look quite old -- perhaps I should be using canopy instead?

**Comment by yomimono** [comment]
This is really great!  Thanks for writing it up. :)

I don't have a strong opinion on where it should live, but there is [a "help needed" project over on Canopy about porting packages/repositories to topkg](http://canopy.mirage.io/Projects/topkg).  Links in both directions would be a good idea IMO.

**Comment by yomimono** [comment]
It looks like [mirage-block-unix 2.8.2](https://github.com/mirage/mirage-block-unix/releases/tag/v2.8.2) should fix the test failure here - thanks @avsm !

**Comment by avsm** [comment]
sorry, that was my bad to start with, so fixing it shortly :)

**Comment by avsm** [comment]
fixed in https://github.com/ocaml/opam-repository/pull/9257 and merged

**Comment by samoht** [comment]
Thanks for your notes! I have a couple of remarks, I will create a new PR to complete your notes with my notes :-)

**Comment by djs55** [comment]
I look forward to reading your improvements :)

**Pull request merged**
