### PR TITLE
Static News section

### PR DESCRIPTION
**Pull request by voila**
Replaces the existing blogroll with a news section similar to ocaml.org
(See #156)

It retrieves the RSS feeds and create a tmpl/news.html which lists entries chronologically
(it only supports RSS 2 and Atom, right now)
And runs when mirage-www is built.

We also display the 10 latest news on the homepage

comments and suggestions are welcome !

screen shot 2015-01-27 at 10 47 26 am

screen shot 2015-01-28 at 10 25 13 am

### CODE REVIEW

**Comment by amirmc** [comment]
Hi @voila, I'm sorry for the delay in getting to this and thanks for your efforts, they are appreciated! I'll have some time this weekend to look over things.

**Comment by voila** [comment]
I have updated the code so it works  with Syndic 1.2 (the current version in OPAM).
See https://github.com/voila/mirage-www/commit/0c4305744ab13f02e7214a85780af19fb98c4d81

**Comment by samoht** [comment]
I completely missed that PR, sorry. That looks like a good idea, I'm happy to merge if you rebase.

**Comment by voila** [comment]
I'm happy to rebase but I can't build the latest mirage-www. Here's the error I get:

```
File "paper.ml", line 29, characters 27-28:
Error: Unbound value i
Command exited with code 2.
```

Anything obvious I should look into ?

**Pull request closed without merging**
