### PR TITLE
use main repo travis scripts rather than @mor1 fork

### PR DESCRIPTION
**Pull request by mor1**
do not merge until https://github.com/ocaml/ocaml-travisci-skeleton/pull/25 merged

### CODE REVIEW

**Comment by avsm** [comment]
I'm confused -- if you delete the custom IP address in the `config.ml` in this changeset, how does the deployed kernel work?

**Comment by mor1** [comment]
eh? src/config.ml line 26 specifies the ip for the deployed image.

**Comment by avsm** [comment]
Ah, it's hardcoded into the mirage-www repo now then.  Not ideal -- wouldn't it be better to be able to specify this via an environment variable and have that passed in from the deployment script?

**Comment by mor1** [comment]
well, it always was hardcoded -- just in a `.travis-config.ml` file rather than the main `src/config.ml` file; the `.travis-config.ml` file was copied over `src/config.ml` as part of the travis script.

ideally this would be specified as a parameter to `mirage` -- when are those patches going to hit?

could certainly pull out as an environment var for now though. will update the PR.

**Comment by avsm** [comment]
For now, an environment variable is best. The other configuration patches haven't been reviewed yet.

**Comment by mor1** [comment]
(still not for merge until @ocaml/ocaml-travisci-skeleton#26 merged)

**Comment by mor1** [comment]
this passes when using @mor1/ocaml-travisci-skeleton. wait for @ocaml/ocaml-travisci-skeleton#26 to merge before merging this.

**Comment by mor1** [comment]
@avsm travis passes following @samoht merge of the ocaml-travisci-skeleton pr.

**Comment by amirmc** [comment]
Can this be merged? Travis is green so I assume everything now points to the correct locations.

**Comment by mor1** [comment]
i believe so. @avsm any further comment?

**Pull request merged**
