### PR TITLE
pages.ml: Added missing space

### PR DESCRIPTION
**Pull request by elimisteve**

### CODE REVIEW

**Comment by talex5** [comment]
OK, if you rebase on `master` it should pass now! (#648 has been merged)

**Comment by elimisteve** [comment]
@talex5 Done! Aaand all tests/checks passed :+1:

**Comment by talex5** [comment]
I think you may have done the rebase in the wrong direction :-) The `Files changed` tab should only show your change. Try `git rebase origin/master` to fix it...

**Comment by elimisteve** [comment]
@talex5 Oops, I forgot that `mirage/mirage-www` was `upstream` on my machine and not `master`.

Fixed!

**Comment by talex5** [comment]
Thanks - the change should be live a few minutes after CI for `master` finishes!

**Pull request merged**
