### PR TITLE
add size matters blog post

### PR DESCRIPTION
**Pull request by yomimono**
Previously hanging out in a gist somewhere.

/cc @hannesm .

### CODE REVIEW

**Comment by amirmc** [comment]
See also https://github.com/mirage/mirage-www/issues/513.

I think we should make this live on Monday 27th at 2pm UTC.

**Comment by hannesm** [comment]
I reworded intro and conclusion slightly, good to go IMHO (feel free to push any typo/grammar changes directly)

**Comment by amirmc** [comment]
@avsm @mor1, Are the deploy scripts all working again (https://github.com/mirage/mirage-www/issues/531)? i.e. when we push merge on this will the new site go live once Travis is done?

It would be good to get the post live by 2pm GMT

**Comment by mor1** [comment]
Last I saw I think @avsm had some PRs queued to fix, but was waiting for deeper testing or something...? Happy to pick them up again if not.

**Comment by hannesm** [comment]
Should we merge now since CI takes ~20 minutes

**Comment by yomimono** [comment]
@mor1, if I merge do you have time to debug any breakage?

**Comment by avsm** [comment]
Please merge and I'll keep an eye...

**Comment by hannesm** [comment]
@avsm travis finished, mirage-www-deployment contains two commits, but mirage.io is down...

**Comment by hannesm** [comment]
it's online now.

**Pull request merged**
