### PR TITLE
tests: test 4.02 and 4.03, and shift deployment to 4.03 based kernels

### PR DESCRIPTION
**Pull request by avsm**

### CODE REVIEW

**Comment by yomimono** [comment]
The tests failed on unsolvable constraints on this PR.  It's possible this is because of the `mirage-net-xen 1.4.2` pin -- if you're still interested in pushing this PR, perhaps try without those pins?

**Comment by hannesm** [comment]
please note https://github.com/mirage/mirage-www/issues/448 more specifically https://github.com/mirage/mirage-net-xen/issues/39 which is not part of any mirage-net-xen release yet... deploying with mirage-net-xen 1.6.* might lead to service outages..

**Comment by avsm** [comment]
refreshed to use mirage-dev

**Comment by hannesm** [comment]
sorry breakage due to my console change (no `log` anymore; log_s renamed to log, this should likely just switch to Logs, but I'm heading off to a punk concert)

**Comment by avsm** [comment]
what the heck
```
mirage =>
  cd /home/travis/build/mirage/mirage-www/src && ocamlbuild -use-ocamlfind -tags annot,bin_annot -pkg mirage config.cmxs
Fatal error: exception (Invalid_argument "[ocamlgraph] in_degree")
```

**Comment by yomimono** [comment]
Feel free to reopen this, but it looks to me like time has passed it by.

**Pull request closed without merging**
