### PR TITLE
[Testing] Use Mini-OS 0.6 for stack-protector fix

### PR DESCRIPTION
**Pull request by talex5**
Testing with new mirage-xen-libs.git to see if that fixes the problem.

### CODE REVIEW

**Comment by talex5** [comment]
I was only intending this PR to be used for testing. It should be reverted when the new mirage-xen-minios appears in opam-repository (or if @mor1 modifies his script to pin the new version).

**Comment by avsm** [comment]
I have a strong preference for the Travis deployment script to be stored in this repository rather than @mor1's branch which noone else can modify.  Once it moves into a `mirage/ocaml-travis-ci-skeleton` or similar repository, it can go back to be being sourced.

**Comment by mor1** [comment]
hm-- the scripts should be being sourced from `ocaml/ocaml-travisci-skeleton` now that @samoht merged them. i thought i'd already fixed that -- will do so now.

**Comment by mor1** [comment]
(or would you prefer to use a `mirage` fork of that `ocaml/...` repo?)

**Comment by avsm** [comment]
That repository on `ocaml/` is fine for now, but I'd really like to see some minimal documentation in the README explaining how to use the deployment feature.

**Comment by mor1** [comment]
the README in this repo or in the travis skeleton scripts repo?

can add that easily enough either way.

**Comment by avsm** [comment]
the travis scripts -- the place where the shell scripts actually exist, so that other people can use them.

**Pull request merged**
