### PR TITLE
Add blog post about screencasts

### PR DESCRIPTION
**Pull request by amirmc**
These videos also belong on the Videos page but I'll do that another time.

### CODE REVIEW

**Comment by amirmc** [comment]
I'll merge this as soon as CI is green.

**Comment by talex5** [comment]
How do you get to the playlist? I see a player window in the blog that says "Try watching this video on www.youtube.com". That shows some Mirage + OS X stuff with homebrew, but no obvious links to videos for other platforms.

**Comment by mor1** [comment]
Not sure I understand -- I see the first video (1/4) in a player window,
with a little "menu" triple-bar icon at the top left. Clicking that drops
down a list of all 4 videos in the series...


On 17 October 2015 at 13:29, Thomas Leonard <notifications@github.com>
wrote:

> How do you get to the playlist? I see a player window in the blog that
> says "Try watching this video on www.youtube.com". That shows some Mirage
> + OS X stuff with homebrew, but no obvious links to videos for other
> platforms.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mirage/mirage-www/pull/397#issuecomment-148913537>.
>



-- 
Richard Mortier
mort@cantab.net

**Comment by talex5** [comment]
Tried it in another VM and the playlist does appear if you can view it directly in the mirage site; it's only if you get redirected to youtube.com that you miss it. Probably a noscript thing.

**Comment by amirmc** [comment]
Possibly. I wonder that @avsm needs to make the original videos 'public' too -- I believe they're only viewable if you know the exact link (and that might have an effect).

**Comment by avsm** [comment]
They're public now. Does that help @talex5?

**Comment by talex5** [comment]
Yes, now I see them when I click on your name in YouTube. Thanks!

**Pull request merged**
