### PR TITLE
[WIP] spring retreat roundup article

### PR DESCRIPTION
**Pull request by hannesm**

### CODE REVIEW

**Comment by yomimono** [comment]
I've rebased this and changed the publish date to today's, just to get it later than the MSA01 announcement which caused the previous merge conflict, and also added a little content about the PVH work.

**Comment by hannesm** [comment]
thanks mindy! imho good to merge (i just pushed a syntax error which will hopefully make the CI happy).

**Comment by hannesm** [comment]
will merge when CI is green (unless someone objects) -- i adjusted the date and linked to lynxis' blog post.

**Comment by gasche** [comment]
(For the record, I sent a post of my own to @Armael for publishing on [Gagallium](http://gallium.inria.fr/blog/), and it's somewhere in the blog pipeline.)

**Pull request merged**
