### PR TITLE
Update dream

### PR DESCRIPTION
**Pull request by TheLortex**
I have enabled ocaml-ci on my dream fork and opened a PR with the sufficient changes to make the CI happy: https://github.com/TheLortex/dream/pull/3

This PR changes the dream commit to point to the updated version.

### CODE REVIEW

**Comment by hannesm** [comment]
Thanks a lot. When I interpret the CI correctly, we need a mirage release to be able to use mirage-crypto-rng 0.11.0.

**Comment by samoht** [comment]
The `fmt` issue is fixed in https://github.com/mirage/mirage-www/pull/800

**Comment by hannesm** [comment]
The deployability CI failure:
```
==> Using 1 locally scanned package as the target.
[WARNING] Unknown variable "ocaml-system:version"
[WARNING] Unknown variable "ocaml-base-compiler:version"
[WARNING] Unknown variable "ocaml-variants:version"
[WARNING] Unknown variable "ocaml-system:version"
[WARNING] Unknown variable "ocaml-base-compiler:version"
[WARNING] Unknown variable "ocaml-variants:version"
opam-monorepo: [ERROR] Solving opam-provided dependencies could not find a solution
[WARNING] Unknown variable "ocaml-system:version"
[WARNING] Unknown variable "ocaml-base-compiler:version"
[WARNING] Unknown variable "ocaml-variants:version"
[WARNING] Unknown variable "ocaml-system:version"
[WARNING] Unknown variable "ocaml-base-compiler:version"
[WARNING] Unknown variable "ocaml-variants:version"
[WARNING] Unknown variable "ocaml-system:version"
[WARNING] Unknown variable "ocaml-base-compiler:version"
[WARNING] Unknown variable "ocaml-variants:version"
[WARNING] Unknown variable "ocaml-system:version"
[WARNING] Unknown variable "ocaml-base-compiler:version"
[WARNING] Unknown variable "ocaml-variants:version"
[WARNING] Unknown variable "ocaml-system:version"
[WARNING] Unknown variable "ocaml-base-compiler:version"
[WARNING] Unknown variable "ocaml-variants:version"
[WARNING] Unknown variable "ocaml-system:version"
[WARNING] Unknown variable "ocaml-base-compiler:version"
[WARNING] Unknown variable "ocaml-variants:version"
opam-monorepo: [ERROR] Can't find all required versions.
Selected: conf-libseccomp.1 conf-which.1 mirage.4.3.3 ocaml-solo5.0.8.1
          ocaml-src.4.13.1 opam-monorepo.0.3.5 solo5.0.7.5
          ocaml-base-compiler&www-hvt ocaml-base-compiler ocaml-base-compiler
          ocaml gmp ocaml-base-compiler
- angstrom -> angstrom.0.15.0
    User requested = 0.15.0
- arp -> arp.3.0.0
    User requested = 3.0.0
- asn1-combinators -> asn1-combinators.0.2.6
    User requested = 0.2.6
- astring -> astring.0.8.5+dune
    User requested = 0.8.5+dune
- base -> base.v0.15.1
    User requested = v0.15.1
- base-bigarray -> base-bigarray.base
    User requested = base
- base-bytes -> base-bytes.base+dune
    User requested = base+dune
- base-threads -> base-threads.base
    User requested = base
- base-unix -> base-unix.base
    User requested = base
- base64 -> base64.3.5.1
    User requested = 3.5.1
- bheap -> bheap.2.0.0
    User requested = 2.0.0
- bigarray-compat -> bigarray-compat.1.1.0
    User requested = 1.1.0
- bigarray-overlap -> bigarray-overlap.0.2.1
    User requested = 0.2.1
- bigstringaf -> bigstringaf.0.9.0
    User requested = 0.9.0
- bos -> bos.0.2.1+dune
    User requested = 0.2.1+dune
- camlp-streams -> camlp-streams.5.0.1
    User requested = 5.0.1
- caqti -> caqti.1.9.0
    User requested = 1.9.0
- caqti-lwt -> caqti-lwt.1.9.0
    User requested = 1.9.0
- cmdliner -> cmdliner.1.1.1+dune
    User requested = 1.1.1+dune
- conf-gmp -> conf-gmp.4
    User requested = 4
- conf-gmp-powm-sec -> conf-gmp-powm-sec.3
    User requested = 3
- conf-libev -> conf-libev.4-12
    User requested = 4-12
- conf-libssl -> conf-libssl.4
    User requested = 4
- conf-m4 -> conf-m4.1
    User requested = 1
- conf-pkg-config -> conf-pkg-config.2
    User requested = 2
- cppo -> cppo.1.6.9
    User requested = 1.6.9
- crunch -> crunch.3.3.1
    User requested = 3.3.1
- csexp -> csexp.1.5.1
    User requested = 1.5.1
- cstruct -> cstruct.6.1.1
    User requested = 6.1.1
- cstruct-lwt -> cstruct-lwt.6.1.1
    User requested = 6.1.1
- cstruct-sexp -> cstruct-sexp.6.1.1
    User requested = 6.1.1
- ctypes -> ctypes.0.20.1+dune
    User requested = 0.20.1+dune
- digestif -> digestif.1.1.3
    User requested = 1.1.3
- dns -> dns.7.0.0
    User requested = 7.0.0
- dns-certify -> dns-certify.7.0.0
    User requested = 7.0.0
- dns-mirage -> dns-mirage.7.0.0
    User requested = 7.0.0
- dns-tsig -> dns-tsig.7.0.0
    User requested = 7.0.0
- domain-name -> domain-name.0.4.0
    User requested = 0.4.0
- dream -> dream.dev
    User requested = dev
- dream-httpaf -> dream-httpaf.dev
    User requested = dev
- dream-mirage -> dream-mirage.dev
    User requested = dev
- dream-pure -> dream-pure.dev
    User requested = dev
- dune -> dune.3.7.0
    User requested = 3.7.0
- dune-configurator -> dune-configurator.3.7.0
    User requested = 3.7.0
- duration -> duration.0.2.1
    User requested = 0.2.1
- emile -> emile.1.1
    User requested = 1.1
- eqaf -> eqaf.0.9
    User requested = 0.9
- ethernet -> ethernet.3.0.0
    User requested = 3.0.0
- faraday -> faraday.0.8.2
    User requested = 0.8.2
- faraday-lwt -> faraday-lwt.0.8.2
    User requested = 0.8.2
- faraday-lwt-unix -> faraday-lwt-unix.0.8.2
    User requested = 0.8.2
- findlib -> findlib.1.9.5+dune
    User requested = 1.9.5+dune
- fmt -> fmt.0.9.0+dune
    User requested = 0.9.0+dune
- fpath -> fpath.0.7.3+dune
    User requested = 0.7.3+dune
- functoria -> functoria.4.3.3
    mirage 4.3.3 requires = 4.3.3
- gmap -> gmap.0.3.0
    User requested = 0.3.0
- gmp -> gmp.6.2.1-4
    User requested = 6.2.1-4
- graphql -> graphql.0.14.0
    User requested = 0.14.0
- graphql-lwt -> graphql-lwt.0.14.0
    User requested = 0.14.0
- graphql_parser -> graphql_parser.0.14.0
    User requested = 0.14.0
- hkdf -> hkdf.1.0.4
    User requested = 1.0.4
- hmap -> hmap.0.8.1+dune
    User requested = 0.8.1+dune
- integers -> integers.0.7.0
    User requested = 0.7.0
- ipaddr -> ipaddr.5.3.1
    User requested = 5.3.1
- ipaddr-sexp -> ipaddr-sexp.5.3.1
    User requested = 5.3.1
- ke -> ke.0.6
    User requested = 0.6
- letsencrypt -> letsencrypt.0.5.0
    User requested = 0.5.0
- logs -> logs.0.7.0+dune2
    User requested = 0.7.0+dune2
- lru -> lru.0.3.1
    User requested = 0.3.1
- lwt -> lwt.5.6.1
    User requested = 5.6.1
- lwt-dllist -> lwt-dllist.1.0.1
    User requested = 1.0.1
- lwt_ppx -> lwt_ppx.2.1.0
    User requested = 2.1.0
- lwt_ssl -> lwt_ssl.1.2.0
    User requested = 1.2.0
- macaddr -> macaddr.5.3.1
    User requested = 5.3.1
- macaddr-cstruct -> macaddr-cstruct.5.3.1
    User requested = 5.3.1
- magic-mime -> magic-mime.1.3.0
    User requested = 1.3.0
- memtrace-mirage -> memtrace-mirage.0.2.1.2.2
    User requested = 0.2.1.2.2
- menhir -> menhir.20220210
    User requested = 20220210
- menhirLib -> menhirLib.20220210
    User requested = 20220210
- menhirSdk -> menhirSdk.20220210
    User requested = 20220210
- metrics -> metrics.0.4.0
    User requested = 0.4.0
- metrics-influx -> metrics-influx.0.4.0
    User requested = 0.4.0
- metrics-lwt -> metrics-lwt.0.4.0
    User requested = 0.4.0
- mimic -> mimic.0.0.6
    User requested = 0.0.6
- mirage-bootvar-solo5 -> mirage-bootvar-solo5.0.6.0
    User requested = 0.6.0
- mirage-clock -> mirage-clock.4.2.0
    User requested = 4.2.0
- mirage-clock-solo5 -> mirage-clock-solo5.4.2.0
    User requested = 4.2.0
- mirage-clock-unix -> mirage-clock-unix.4.2.0
    User requested = 4.2.0
- mirage-crypto -> mirage-crypto.0.11.0
    User requested = 0.11.0
- mirage-crypto-ec -> mirage-crypto-ec.0.11.0
    User requested = 0.11.0
- mirage-crypto-pk -> mirage-crypto-pk.0.11.0
    User requested = 0.11.0
- mirage-crypto-rng -> mirage-crypto-rng.0.11.0
    User requested = 0.11.0
- mirage-crypto-rng-lwt -> mirage-crypto-rng-lwt.0.11.0
    User requested = 0.11.0
- mirage-crypto-rng-mirage -> mirage-crypto-rng-mirage.0.11.0
    User requested = 0.11.0
- mirage-flow -> mirage-flow.3.0.0
    User requested = 3.0.0
- mirage-kv -> mirage-kv.6.1.0
    User requested = 6.1.0
- mirage-kv-mem -> mirage-kv-mem.3.2.1
    User requested = 3.2.1
- mirage-logs -> mirage-logs.1.2.0
    User requested = 1.2.0
- mirage-monitoring -> mirage-monitoring.0.0.3
    User requested = 0.0.3
- mirage-net -> mirage-net.4.0.0
    User requested = 4.0.0
- mirage-net-solo5 -> mirage-net-solo5.0.8.0
    User requested = 0.8.0
- mirage-profile -> mirage-profile.0.9.1
    User requested = 0.9.1
- mirage-random -> mirage-random.3.0.0
    User requested = 3.0.0
- mirage-runtime -> (problem)
    User requested = 4.3.4
    mirage 4.3.3 requires = 4.3.3
    Rejected candidates:
      mirage-runtime.4.3.4: Incompatible with restriction: = 4.3.3
- mirage-solo5 -> mirage-solo5.0.9.1
    User requested = 0.9.1
- mirage-stack -> mirage-stack.4.0.0
    User requested = 4.0.0
- mirage-time -> mirage-time.3.0.0
    User requested = 3.0.0
- mirage-unix -> mirage-unix.5.0.1
    User requested = 5.0.1
- mirageio -> mirageio.zdev
    User requested = zdev
- mtime -> mtime.2.0.0+dune
    User requested = 2.0.0+dune
- multipart_form -> multipart_form.0.4.1
    User requested = 0.4.1
- multipart_form-lwt -> multipart_form-lwt.0.4.1
    User requested = 0.4.1
- num -> num.1.4+dune2
    User requested = 1.4+dune2
- ocaml -> ocaml.4.13.1
    User requested = 4.13.1
- ocaml-base-compiler -> ocaml-base-compiler.4.13.1
    User requested = 4.13.1
- ocaml-compiler-libs -> ocaml-compiler-libs.v0.12.4
    User requested = v0.12.4
- ocaml-config -> ocaml-config.2
    User requested = 2
- ocaml-options-vanilla -> ocaml-options-vanilla.1
    User requested = 1
- ocaml-syntax-shims -> ocaml-syntax-shims.1.0.0
    User requested = 1.0.0
- ocamlfind -> ocamlfind.1.9.5+dune
    User requested = 1.9.5+dune
- ocplib-endian -> ocplib-endian.1.2
    User requested = 1.2
- omd -> omd.2.0.0~alpha2
    User requested = 2.0.0~alpha2
- optint -> optint.0.3.0
    User requested = 0.3.0
- parse-argv -> parse-argv.0.2.0
    User requested = 0.2.0
- parsexp -> parsexp.v0.15.0
    User requested = v0.15.0
- pbkdf -> pbkdf.1.2.0
    User requested = 1.2.0
- pecu -> pecu.0.6
    User requested = 0.6
- ppx_cstruct -> ppx_cstruct.6.1.1
    User requested = 6.1.1
- ppx_derivers -> ppx_derivers.1.2.1
    User requested = 1.2.1
- ppx_deriving -> ppx_deriving.5.2.1
    User requested = 5.2.1
- ppx_deriving_yaml -> ppx_deriving_yaml.0.2.1
    User requested = 0.2.1
- ppx_sexp_conv -> ppx_sexp_conv.v0.15.1
    User requested = v0.15.1
- ppxlib -> ppxlib.0.29.1
    User requested = 0.29.1
- prettym -> prettym.0.0.3
    User requested = 0.0.3
- psq -> psq.0.2.1
    User requested = 0.2.1
- ptime -> ptime.1.0.0+dune2
    User requested = 1.0.0+dune2
- randomconv -> randomconv.0.1.3
    User requested = 0.1.3
- re -> re.1.10.4
    User requested = 1.10.4
- result -> result.1.5
    User requested = 1.5
- rresult -> rresult.0.7.0+dune
    User requested = 0.7.0+dune
- seq -> seq.base+dune
    User requested = base+dune
- sexplib -> sexplib.v0.15.1
    User requested = v0.15.1
- sexplib0 -> sexplib0.v0.15.1
    User requested = v0.15.1
- ssl -> ssl.0.5.13
    User requested = 0.5.13
- stdlib-shims -> stdlib-shims.0.3.0
    User requested = 0.3.0
- stringext -> stringext.1.6.0
    User requested = 1.6.0
- tailwindcss -> tailwindcss.dev
    User requested = dev
- tcpip -> tcpip.7.1.2
    User requested = 7.1.2
- tls -> tls.0.16.0
    User requested = 0.16.0
- tls-mirage -> tls-mirage.0.16.0
    User requested = 0.16.0
- unstrctrd -> unstrctrd.0.3
    User requested = 0.3
- uri -> uri.4.2.0
    User requested = 4.2.0
- uutf -> uutf.1.0.3+dune
    User requested = 1.0.3+dune
- www-hvt -> www-hvt.zdev
    User requested = zdev
- x509 -> x509.0.16.4
    User requested = 0.16.4
- yaml -> yaml.3.1.0
    User requested = 3.1.0
- yojson -> yojson.2.0.2
    User requested = 2.0.2
- zarith -> zarith.1.12+dune+mirage1
    User requested = 1.12+dune+mirage1
removing overlay repository [opam-overlays, mirage-overlays]
Repositories removed from the selections of switch 4.13. Use '--all' to forget about them altogether.
Repositories removed from the selections of switch 4.13. Use '--all' to forget about them altogether.
make[2]: *** [Makefile:36: mirage/mirage/www-hvt.opam.locked] Error 1
make[1]: *** [Makefile:39: lock] Error 2
make: *** [Makefile:51: depend] Error 2
```

Would it help to (a) restrict mirage-runtime as well to dune < 3.7 or (b) should we remove the dune bound on mirage 4.3.4 (and leave it open for chamelon users to get failures?)? Any idea what is the path forward (to me it looks like https://github.com/tarides/opam-monorepo/issues/378 https://github.com/tarides/opam-monorepo/issues/342 https://github.com/tarides/opam-monorepo/issues/331 -- all reported and no solution in sight).

**Comment by hannesm** [comment]
Merging, thanks a lot. The CI failures, as mentioned by @samoht: fmt addressed in #800 ; dream-httpaf requiring a bound on ke https://github.com/TheLortex/dream/pull/4

**Pull request merged**
