### PR TITLE
add irmin v2 blog post reference

### PR DESCRIPTION
**Pull request by avsm**
cc @samoht

### CODE REVIEW

**Comment by samoht** [comment]
```
File "dispatch.mli", line 52, characters 36-43:
Error: Unbound type constructor Clock.t
```
I'm having a look at fixing this.

**Comment by hannesm** [comment]
that `Clock.t` is gone... it used to be `unit`.

**Comment by samoht** [comment]
The compilation issue should be fixed by https://github.com/mirage/mirage-www/pull/660

**Comment by samoht** [comment]
Rebased

**Pull request merged**
